# permissions for end users to view wideguards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wideguard-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wideguard-operator
    app.kubernetes.io/part-of: wideguard-operator
    app.kubernetes.io/managed-by: kustomize
  name: wideguard-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - wideguards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - wideguards/status
  verbs:
  - get
